# Generated by Django 5.1 on 2025-01-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
