# Generated by Django 5.1 on 2025-01-21 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='lists.list'),
            preserve_default=False,
        ),
    ]
