# Generated by Django 5.1 on 2025-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('where_to_buy', models.TextField(blank=True)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='incomplete', max_length=15)),
                ('is_open', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
