# Generated by Django 5.1 on 2025-01-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recipients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipients.recipient'),
        ),
    ]
