# Generated by Django 5.1 on 2025-01-21 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('recipients', '0002_recipient_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recipients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipients.recipient'),
            preserve_default=False,
        ),
    ]
