# Generated by Django 5.1 on 2025-01-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='recipients',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
