# Generated by Django 5.1 on 2025-01-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='budget',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
