# Generated by Django 5.1.5 on 2025-01-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user_id',
        ),
    ]
